/*
 * Created on 13 Feb 2016 ( Time 21:09:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.pawsey.api.service;

import org.springframework.stereotype.Service;

import javax.security.auth.login.CredentialException;

import java.util.List;

/**
 * Base buisiness-logic service interface. A list of simple CRUD operations is provided.
 *
 * @param <T> The main entity type to be acted on by this service.
 */
@Service
public interface BaseService<T>
{
	T create(T entity) throws Exception;

	T findById(Integer id);

	List<T> findAll();

	T update(T entity);

	void delete(T credentials);
}
